/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as ProducaoRouteImport } from './routes/producao'
import { Route as MateriasPrimasRouteImport } from './routes/materias-primas'

const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducaoRoute = ProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriasPrimasRoute = MateriasPrimasRouteImport.update({
  id: '/materias-primas',
  path: '/materias-primas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/materias-primas': typeof MateriasPrimasRoute
  '/producao': typeof ProducaoRoute
  '/produtos': typeof ProdutosRoute
}
export interface FileRoutesByTo {
  '/materias-primas': typeof MateriasPrimasRoute
  '/producao': typeof ProducaoRoute
  '/produtos': typeof ProdutosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/materias-primas': typeof MateriasPrimasRoute
  '/producao': typeof ProducaoRoute
  '/produtos': typeof ProdutosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/materias-primas' | '/producao' | '/produtos'
  fileRoutesByTo: FileRoutesByTo
  to: '/materias-primas' | '/producao' | '/produtos'
  id: '__root__' | '/materias-primas' | '/producao' | '/produtos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MateriasPrimasRoute: typeof MateriasPrimasRoute
  ProducaoRoute: typeof ProducaoRoute
  ProdutosRoute: typeof ProdutosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producao': {
      id: '/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof ProducaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materias-primas': {
      id: '/materias-primas'
      path: '/materias-primas'
      fullPath: '/materias-primas'
      preLoaderRoute: typeof MateriasPrimasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  MateriasPrimasRoute: MateriasPrimasRoute,
  ProducaoRoute: ProducaoRoute,
  ProdutosRoute: ProdutosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
