/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatorioDeProducaoRouteImport } from './routes/relatorio-de-producao'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as MateriasPrimasRouteImport } from './routes/materias-primas'

const RelatorioDeProducaoRoute = RelatorioDeProducaoRouteImport.update({
  id: '/relatorio-de-producao',
  path: '/relatorio-de-producao',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriasPrimasRoute = MateriasPrimasRouteImport.update({
  id: '/materias-primas',
  path: '/materias-primas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/materias-primas': typeof MateriasPrimasRoute
  '/produtos': typeof ProdutosRoute
  '/relatorio-de-producao': typeof RelatorioDeProducaoRoute
}
export interface FileRoutesByTo {
  '/materias-primas': typeof MateriasPrimasRoute
  '/produtos': typeof ProdutosRoute
  '/relatorio-de-producao': typeof RelatorioDeProducaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/materias-primas': typeof MateriasPrimasRoute
  '/produtos': typeof ProdutosRoute
  '/relatorio-de-producao': typeof RelatorioDeProducaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/materias-primas' | '/produtos' | '/relatorio-de-producao'
  fileRoutesByTo: FileRoutesByTo
  to: '/materias-primas' | '/produtos' | '/relatorio-de-producao'
  id: '__root__' | '/materias-primas' | '/produtos' | '/relatorio-de-producao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MateriasPrimasRoute: typeof MateriasPrimasRoute
  ProdutosRoute: typeof ProdutosRoute
  RelatorioDeProducaoRoute: typeof RelatorioDeProducaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorio-de-producao': {
      id: '/relatorio-de-producao'
      path: '/relatorio-de-producao'
      fullPath: '/relatorio-de-producao'
      preLoaderRoute: typeof RelatorioDeProducaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materias-primas': {
      id: '/materias-primas'
      path: '/materias-primas'
      fullPath: '/materias-primas'
      preLoaderRoute: typeof MateriasPrimasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  MateriasPrimasRoute: MateriasPrimasRoute,
  ProdutosRoute: ProdutosRoute,
  RelatorioDeProducaoRoute: RelatorioDeProducaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
